# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  apiteste:
    image: apiteste
    build:
      context: .
      dockerfile: ApiTeste/Dockerfile
    ports:
      - 5220:5220
